[2024-11-03T16:27:48.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T16:27:48.429+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.get_review_data manual__2024-11-03T16:26:27.332006+00:00 [queued]>
[2024-11-03T16:27:48.432+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.get_review_data manual__2024-11-03T16:26:27.332006+00:00 [queued]>
[2024-11-03T16:27:48.432+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 4
[2024-11-03T16:27:48.436+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_review_data> on 2024-11-03 16:26:27.332006+00:00
[2024-11-03T16:27:48.439+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=381) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T16:27:48.439+0000] {standard_task_runner.py:72} INFO - Started process 383 to run task
[2024-11-03T16:27:48.440+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'get_review_data', 'manual__2024-11-03T16:26:27.332006+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpmarnu8k8']
[2024-11-03T16:27:48.441+0000] {standard_task_runner.py:105} INFO - Job 123: Subtask get_review_data
[2024-11-03T16:27:48.457+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.get_review_data manual__2024-11-03T16:26:27.332006+00:00 [running]> on host 2b8c286c59ee
[2024-11-03T16:27:48.483+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='get_review_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T16:26:27.332006+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T16:26:27.332006+00:00'
[2024-11-03T16:27:48.484+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T16:27:53.878+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-03T16:27:53.893+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T16:27:53.894+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=get_review_data, run_id=manual__2024-11-03T16:26:27.332006+00:00, execution_date=20241103T162627, start_date=20241103T162748, end_date=20241103T162753
[2024-11-03T16:27:53.911+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-03T16:27:53.927+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-03T16:27:53.928+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
