[2024-10-30T18:12:11.977+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T18:12:11.986+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_db_user_data manual__2024-10-30T18:12:05.893765+00:00 [queued]>
[2024-10-30T18:12:11.990+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transfer_task_db_user_data manual__2024-10-30T18:12:05.893765+00:00 [queued]>
[2024-10-30T18:12:11.991+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T18:12:11.996+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): transfer_task_db_user_data> on 2024-10-30 18:12:05.893765+00:00
[2024-10-30T18:12:11.999+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T18:12:12.001+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2024-10-30T18:12:12.001+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'transfer_task_db_user_data', 'manual__2024-10-30T18:12:05.893765+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp91jh9nrk']
[2024-10-30T18:12:12.001+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask transfer_task_db_user_data
[2024-10-30T18:12:12.033+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.transfer_task_db_user_data manual__2024-10-30T18:12:05.893765+00:00 [running]> on host 6bca134bba56
[2024-10-30T18:12:12.071+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transfer_task_db_user_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T18:12:05.893765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T18:12:05.893765+00:00'
[2024-10-30T18:12:12.072+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T18:12:12.078+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-30T18:12:12.079+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    gcloud sql import csv dockdecoder:us-east4:data-wharehousing gs://Data/Raw_CSV/TEST//TEST.csv     --database=postgres     --table=user_reviews_test\n    ']
[2024-10-30T18:12:12.084+0000] {subprocess.py:86} INFO - Output:
[2024-10-30T18:12:12.086+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 2: gcloud: command not found
[2024-10-30T18:12:12.086+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-10-30T18:12:12.094+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-10-30T18:12:12.103+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=transfer_task_db_user_data, run_id=manual__2024-10-30T18:12:05.893765+00:00, execution_date=20241030T181205, start_date=20241030T181211, end_date=20241030T181212
[2024-10-30T18:12:12.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T18:12:12.133+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task transfer_task_db_user_data (Bash command failed. The command returned a non-zero exit code 127.; 87)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-10-30T18:12:12.144+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-30T18:12:12.155+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T18:12:12.156+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
