[2024-11-01T19:36:56.397+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-01T19:36:56.404+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_meta_data manual__2024-11-01T19:36:55.392647+00:00 [queued]>
[2024-11-01T19:36:56.407+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_meta_data manual__2024-11-01T19:36:55.392647+00:00 [queued]>
[2024-11-01T19:36:56.407+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-01T19:36:56.413+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_table_meta_data> on 2024-11-01 19:36:55.392647+00:00
[2024-11-01T19:36:56.418+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-01T19:36:56.419+0000] {standard_task_runner.py:72} INFO - Started process 149 to run task
[2024-11-01T19:36:56.420+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_meta_data', 'manual__2024-11-01T19:36:55.392647+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpc4lf__xj']
[2024-11-01T19:36:56.422+0000] {standard_task_runner.py:105} INFO - Job 214: Subtask create_table_meta_data
[2024-11-01T19:36:56.456+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.create_table_meta_data manual__2024-11-01T19:36:55.392647+00:00 [running]> on host eb7019e3fc71
[2024-11-01T19:36:56.493+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_meta_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T19:36:55.392647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T19:36:55.392647+00:00'
[2024-11-01T19:36:56.494+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-01T19:36:57.605+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-01T19:36:57.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-01T19:36:57.613+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_meta_data, run_id=manual__2024-11-01T19:36:55.392647+00:00, execution_date=20241101T193655, start_date=20241101T193656, end_date=20241101T193657
[2024-11-01T19:36:57.630+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-01T19:36:57.641+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-01T19:36:57.642+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
